[platformio]
src_dir = .

[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
board_build.flash_size = 16MB
board_upload.flash_size = 16MB
board_build.partitions = default_16MB.csv
board_build.arduino.memory_type = qio_opi
board_build.psram_type = opi
build_flags =
  -DBOARD_HAS_PSRAM
lib_deps =
  homespan/HomeSpan@1.9.1
  crankyoldgit/IRremoteESP8266
  adafruit/DHT sensor library
  adafruit/Adafruit Unified Sensor
build_src_filter =
  +<*.ino>
  +<*.cpp>
  +<*.h>
  -<.git/>
  -<Case/>
  -<images/>
